### ISSUE TITLE
500 Internal Server Error when applying filter to user list in "Administration -> Users"

### ISSUE THREAD

**Issue by saric** [kubitron/redmine_git_hosting#69] opened 2012-09-26 14:25 UTC
My Redmine config:
- Redmine 1.4.4.stable
- Rails 2.3.14
- ruby 1.8.7
- Phusion Passenger 3.0.12
- nginx 1.3.5
- mysql 5.1
- Scientific Linux 6.1
- Redmine is installed in subURI.

Testing was done on clean Redmine installation (fresh install without any other plugins) and using redmine_git_hosting from testing branch.

When I click "Apply" button in "Administration -> Users" (to filter user list by username), Redmine gives 500 Internal Server Error.

Logged error in production.log:

<pre>Processing UsersController#index (for 192.168.239.45 at 2012-09-26 16:20:34) [GET]
  Parameters: {"action"=>"index", "status"=>"1", "name"=>"a", "controller"=>"users"}

NoMethodError (undefined method `call' for nil:NilClass):
  app/controllers/users_controller.rb:44:in `index'
  passenger (3.0.12) lib/phusion_passenger/rack/request_handler.rb:96:in `process_request'
  passenger (3.0.12) lib/phusion_passenger/abstract_request_handler.rb:513:in `accept_and_process_next_request'
  passenger (3.0.12) lib/phusion_passenger/abstract_request_handler.rb:274:in `main_loop'
...</pre>

I've noticed the similar error as in redmine_ldap_sync plugin (resolved):
https://github.com/thorin/redmine_ldap_sync/issues/42

**Comment by frasten** [comment] 2012-09-26 15:16
This issue could be related to #67.

**Comment by kubitron** [comment] 2012-09-26 17:36
Could you pull the latest from 'testing' and see if the error is still there?

**Comment by frasten** [comment] 2012-09-26 17:41
Hi, unfortunately running commit b445672b92 the issue is still here: http://pastie.org/4810293

**Comment by kubitron** [comment] 2012-09-26 17:45
Yup.  I have reproduced it.  Sorry for the delay.  I'll get to it as soon as I can (may not be for a couple of hours).

Really sorry for this speed-bump.  Lots of code got changed in this upgrade.

**Comment by kubitron** [comment] 2012-09-27 00:16
Ok.  Give this a try.  Your pointer to thorin/redmine_ldap_sync#42 was useful, but not entirely sure why this matters (ah the mysteries of Rails).

**Comment by kubitron** [comment] 2012-09-27 03:57
(p.s. I meant try the testing branch again).

**Comment by frasten** [comment] 2012-09-27 06:36
Using commit 81895d3, same issue. Here is the log: http://pastie.org/4825230

**Comment by saric** [comment] 2012-09-27 10:33
I've upgraded to commit 81895d3, and it is working fine now.

**Comment by kubitron** [comment] 2012-09-27 15:33
Great!  I'm going to close this bug.

**Closed as completed by kubitron** 2012-09-27 15:33 UTC
Labels: 0 - Bug with Plugin, A - Show-Stopper

**Comment by kubitron** [comment] 2012-09-27 16:57
So -- any more issues with the plugin?  Is it working?

**Comment by frasten** [comment] 2012-09-28 08:47
Unfortunately, I'm still affected from this bug. :-(
Using commit 2591c8f32100, testing branch.
[This](http://pastie.org/4851164) is my `script/about`, and [this](http://pastie.org/4851211) is the log (in debug mode) when typing `admin` in the filter field and hitting enter.
Thank you!

**Comment by saric** [comment] 2012-09-28 11:08
I use very similar config, with following differences:
- redmine_git_hosting is the only installed Redmine plugin, and
- RubyGems version          1.8.12
  Please, check the requirements for Redmine v1.4.x:
  RubyGems <= 1.8
  http://www.redmine.org/projects/redmine/wiki/RedmineInstall
  I had this problem before commit 81895d3.

**Comment by kubitron** [comment] 2012-09-28 12:25
@frasten, can you try removing the other two plugins (i.e. keep redmine_git_hosting)?  This bug is a very weird problem that plugins seem to cause.

**Comment by frasten** [comment] 2012-09-28 12:32
@kubitron: sure, now I've tried to remove the other plugins. script/about says that only redmine_git_hosting is installed, but I've been able to reproduce the same issue. Note that in my case this isn't a showstopper for sure: I've only a handful of users :-) .

**Comment by kubitron** [comment] 2012-09-28 12:44
@frasten, can you make sure that you have the fix?  Look at:

```
vendor/plugins/redmine_git_hostin/lib/git_hosting/patches/user_patch.rb
```

At the top, it should say:

```
require_dependency 'project'
require_dependency 'git_hosting'
```

It should _not_ say:

```
require_dependency 'principle'
require_dependency 'user'
require_dependency 'git_hosting'
```

**Comment by frasten** [comment] 2012-09-28 13:18
That file is exactly like you said. I retried again, but I still get a 500 error.

**Comment by kubitron** [comment] 2012-09-28 13:55
Hm... I compared our installations.  My rubyGems is version 1.8.21 and it seems to work.  Perhaps you could try upgrading?  @saric, what version of rubyGems are you using?

**Comment by saric** [comment] 2012-09-28 13:59
Hi John,
as I said, I'm using RubyGems v1.8.12.

**Comment by kubitron** [comment] 2012-09-28 14:01
@saric, question for you -- since you are using passenger, have you gotten the Web view of repositories working?  I have a tester that is experiencing problems that seem to be related to the setting of $HOME (although I haven't verified this yet).

p.s. Missed your earlier comment on RubyGems version.   @frasten, see if upgrading RubyGems helps...

**Comment by frasten** [comment] 2012-09-28 14:15
@kubitron : Upgraded to RubyGems v1.8.21: http://pastie.org/4855848, but this issue is still here.

**Comment by kubitron** [comment] 2012-09-30 01:42
@saric, I did something different to fix this problem.  Can you grab from the head of the testing branch and see if the problem is still fixed?
