### ISSUE TITLE
Handle New Multiple Repos/Project Feature for Redmine

### ISSUE THREAD

**Issue by kubitron** [kubitron/redmine_git_hosting#8] opened 2012-01-30 22:28 UTC
This is a general feature request for compatibility of redmine_git_hosting plugin with the new multiple repository per project feature currently being developed for Redmine 1.4 (or at least > 1.3).

Incidentally, I haven't started implementing anything yet.  This feature will fundamentally change the path-handling code of the plugin (as far as I can tell).  It will also touch a bunch of the support screens and change the process of setting up new repositories.  Thus -- will probably be a significant rewrite.

For now, please feel free to comment on desirable features you would like in this domain.  No promises, but I'll see what I can do.  At the moment, I am waiting for the new code to stabilize before I start.  Also, I have no idea what this fix will do for compatibility with Chili, possibly further complicating things (I'm not even sure that the plugin is still working well with Chili -- I suppose I need to make a Chili installation sometime).

--KUBI--

**Comment by rcross** [comment] 2012-04-20 12:08
1.4 has been released with multiple-repo support. Any ideas on how to incorporate this yet? I was getting ready to upgrade to the lastest redmine for this reason (and also update to the latest version of this module too) when I noticed this issue. I haven't looked too deep at how redmine is supporting multiple repos, but it doesn't strike me that you would need to significantly rewrite this module unless you wanted to support different permissions per repo or something.

**Comment by kubitron** [comment] 2012-04-21 00:04
Hello.  I haven't had a chance to work on this yet.  

One complicating issue is that the current path logic (pre 1.4) is very explicit about what the name of a repository is (it is related directly to the name of the project, which is guaranteed to be unique).  In 1.4, there is no uniqueness constraint on the name of repositories, so this is going to complicate the very code that I wrote to recover from lots of errors.

I will be looking at this, however, after the term ends and I have some more time.   If you have any ideas on how you would like this to work, please let me know...!

**Comment by rcross** [comment] 2012-04-21 07:43
hmm.. the lack of a uniqueness constraint on the repo names sounds like a bit of a bug in redmine, however I can see how when not using gitosis it is not as important. 

I did see that in the database there is a repo ID being used, so my first thought was to use the project machine name as a prefix plus the id to guarantee uniqueness but that would end up with unfriendly repo names. I think I would approach it either by having this plugin implement some custom validation on that field that enforces the uniqueness OR i would have this module implement a machine_name field that would need to be part of adding a repo (ideally using some javascript to seed it based on the human readable name being used). The latter approach is probably the best.

**Comment by kubitron** [comment] 2012-04-21 17:06
Yes.  I actually spent a bit of time on the Redmine site discussing this "feature" and the non-uniqueness constraint. The Redmine implementers were declaring this as a "feature", since they wanted the ability to have the same repo in multiple projects.  Note that it is not "machine_name" that is the uniqueness constraint.  I would be "project_name", by unfortunately, you would have to be able to allow the case in which the same repo was in different projects.  I haven't look at the final implementation yet, but this issue would require some intrusive rewriting of my code.

**Comment by nvx** [comment] 2012-05-09 16:56
project-name/repo-name would be guaranteed to be unique, no?

**Comment by kubitron** [comment] 2012-05-09 17:27
@nvx, my understanding is that project-name/repo-name is not a good identifier, since the desire is that the same physical repo can be part of multiple projects. Also, even if project-name/repo-name were unique while repo-name wasn't, it would kill off some code that I have in my version of the plugin that can find a repo regardless of which directory it is in (thus making the plugin always able to recover from problems by executing a fetch-changesets operation).  A prime example is that even if a move from one project to another -- which will move repos in the gitolite repository --fails for some reason, my version of the plugin can still recover and correct.

**Comment by nvx** [comment] 2012-05-09 17:31
True. You could just add a uniqueness constraint onto repository names, or add a separate field only for gitolite managed repositories that is used as the repository url seems like the only two options that avoid having to use ugly id numbers or the like in the path.

**Comment by rcross** [comment] 2012-05-21 03:34
perhaps a bit obvious, but the machine name used for projects (which is unique) and is used for the repo name (mostly for convenience and made sense in 1-to-1 relationshop) can be decoupled from this to solve this issue. Basically, the repo would need a machine name field (which would be unique among repo, but could potentially be the same as a project machine name without conflicting), then a little bit of javascript could simply pre-populate the repo machine name field with the project machine name if it is the first repo or not used by other repos. This last part is mostly convenience.  

If the repo id that is already part of the redmine tables allows for alpahnumeric string content, the problem is extra easy. Otherwise, this might make sense to just have a mapping table for numeric repo id to alphanumeric name / path.

**Comment by rcross** [comment] 2012-07-05 06:44
any further ideas on this?

**Comment by kubitron** [comment] 2012-08-21 15:48
Hello @rcross.  I'm going to be looking at 1.4 integration next.  By "machine name", in your previous post, I'm assuming that you mean the project "identifier" or "path"?  Up until now, the path was directly tied to the name of the project.  If there is a uniqueness constraint on the path, then it is easy to correct path changes which result from changes in the parentage of projects. I suppose that I can have an option that enforces uniqueness as on option.   Barring that, I could let users simply type in the name/path in the gitolite repo.

**Comment by kubitron** [comment] 2012-09-26 06:15
Ok.  There is a preliminary version of Redmine 1.4 support on the testing branch.  My final solution for multiple repository support is through the **gitRepositoryIdentUnique** parameter. 
1. If 'true', then repository identifiers must be unique across all repositories and cannot equal project identifiers. In this case, repositories are simply named by their identifiers (or by the project identifier if the repo identifier is blank). 
2. If 'false', then repository identifiers do not need to be unique across repositories, but still cannot equal project identifiers. In this case, repositories are named by project_identifier/repo_identifier, unless the repo_identifier is blank, in which case they are simply named by the project_identifier.

**Comment by kubitron** [comment] 2012-09-27 16:56
Any comments on this?  Is it working for people?

**Comment by gituser** [comment] 2012-09-30 02:29
it's working for me.

**Comment by kubitron** [comment] 2012-10-02 20:11
Ok.  I'm getting close to wanting to move this 1.4 implementation from testing to master.  Any comments from anyone?  Is it still working for people?

**Comment by kubitron** [comment] 2012-10-02 20:16
@rcross, haven't heard from you... I'm about to freeze the testing branch into master (unless I hear any objections).

**Comment by kubitron** [comment] 2012-10-03 19:34
I'm closing this out, since 1.4 support is now exported to master.

**Closed as completed** 2012-10-03 19:42 UTC
Labels: 2 - Feature Request
